### PR TITLE
Added support for Im871A as others have requested

### PR DESCRIPTION
**Pull request by sunsetdk**
Could you please add the support for the Im871A-USB which i have committet.

René

### CODE REVIEW

**Comment by tobiasrask** [comment]
@sunsetdk can you update/add unit tests for these new info-fields (leak, burst, reverse, dry)?

**Comment by sunsetdk** [comment]
I have added unit test, and also added a new meter (custom made meter, but code will be published later for the meter. It is a temp and humidity meter.

**Comment by tobiasrask** [comment]
@sunsetdk are you ready with this PR now? I could merge this to master.

**Comment by sunsetdk** [comment]
Yes, i have added the tests, and i'm have been using the code for days now (with node red), with no problems :)

**Pull request merged**
